### ISSUE TITLE
Exemple in NPM

### ISSUE THREAD

**Issue by aslamcode** [SegFaultx64/express-http-to-https#6]
Hello Guys!! Thank's for de module!!

I want just help other programs in future.

This line is incorrect in NPM example: 

_redirectToHTTPS = require('express-http-to-https')_

Please if possible update this line in NPM example to:

_redirectToHTTPS = require('express-http-to-https').redirectToHTTPS_

Thank's for all!

**Comment by SegFaultx64** [comment]
Closed by e44a018 and version 1.1.3 published to NPM
