### ISSUE TITLE
Unnecessary check

### ISSUE THREAD

**Issue by alexalghisi** [SegFaultx64/express-http-to-https#8]
Could you please explain why this check is needed ?

`(parseInt(req.get('x-forwarded-port'), 10) === parseInt(req.get('x-forwarded-port'), 10))`

**Comment by SegFaultx64** [comment]
This is to makes sure that `req.get('x-forwarded-port')` is an int. `NaN` is not equal to itself as a rule so this will account for that case. Let me know if you have any further questions.
