### ISSUE TITLE
Redundant condition (a === a)

### ISSUE THREAD

**Issue by fearmear** [SegFaultx64/express-http-to-https#9]
https://github.com/SegFaultx64/express-http-to-https/blob/64881ce06e4f8fb0d787fcb086cab34f63867966/index.js#L11

**Comment by SegFaultx64** [comment]
Hi @fearmear 

Sorry for the delay on this. This is a stupid hack, but what is is doing is checking that `x-forwarded-port` is not `NaN`.  [See this Stackoverflow post](https://stackoverflow.com/questions/6976721/is-nan-equal-to-nan/12628417)

**Comment by fearmear** [comment]
This introduces unnecessary complexity. We have built-in `isNaN` function in the language.
